version: "3.7"

services: 
    db:
        image: mysql:latest
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: flask_app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass

    flask:
        image: eisichenko/chat_app_flask:latest
        container_name: flask
        restart: always
        command: gunicorn --worker-class eventlet -w 1 --bind ":8000" --log-level debug app:app
        environment: 
            - ENV=docker-compose
        links: 
            - redis
            - db
        ports:
            - 5000:8000
    redis:
        image: redis
    rq:
        image: eisichenko/chat_app_flask:latest
        command: python3 run-worker.py
        environment: 
            - ENV=rq
        links: 
            - redis
            - flask

volumes: 
    db_data: {}