name: CI

env:
  ENV: github-actions

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setting up MySQL
      run: |
        sudo systemctl enable mysql.service
        sudo systemctl start mysql.service
        mysql -uroot -proot -e "CREATE DATABASE test_flask_app;"
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Testing
      run: |
        coverage run -m pytest -v
    - name: Pushing to dockerhub    
      if: job.status == 'success'
      env:
        DOCKER_USER: eisichenko
        DOCKER_REPO: eisichenko/chat_app_flask
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: bash .scripts/docker_push.sh
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
      
